### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by Abbe98** [Wikimedia-Sverige/ODOK#29]
Accessing users locations won't work because it requires HTTPS in at least in Opera/Chrome...

**Comment by lokal-profil** [comment]
This is a known issue. The problem is that the current server OS is to old for us to install Let's Encrypt and easily turn on https.

A server migration is in the works but I don't have an ETA yet.

**Comment by lokal-profil** [comment]
Should have been solved by server migration
