### ISSUE TITLE
Translation No --> Sv

### ISSUE THREAD

**Issue by Haxpett** [Wikimedia-Sverige/ODOK#30]
Page interpreted as being in Norwegian and my phone asked me if I wanted a translation to Swedish.
![2016-10-03 09 34 31](https://cloud.githubusercontent.com/assets/8407258/19077013/301daaea-8a4b-11e6-8fec-f34366db5715.png)

**Comment by lokal-profil** [comment]
@Haxpett Could you confirm if this is still happening (you might have to clear your cache).

**Comment by Haxpett** [comment]
@lokal-profil Works great now after clearing my cache. No question about translation coming up.
